--- 
abstract: Auto-create NetAddr::IP objects from columns.
author: "Dagfinn Ilmari Manns\xC3\xA5ker, C<< <ilmari at ilmari.org> >>"
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBIx-Class-InflateColumn-IP
no_index: 
  directory: 
    - inc
    - t
requires: 
  DBIx::Class: 0.07005
  NetAddr::IP: 0
  perl: 5.6.1
tests: t/*.t
version: 0.02000
